### DISCUSSION TITLE
Real examples of the action usage

### DISCUSSION THREAD

**Discussion by machulav** [machulav/ec2-github-runner#19] [Show and tell]
Hey, welcome! 

In this discussion, I will collect all the real examples of the `ec2-github-runner` action usage I'm aware of.

Feel free to add your story as well 🙌

If you have any questions, please create a new discussion or issue.

**Comment by machulav** [comment]
@lielran shared in [the comment](https://github.com/machulav/ec2-github-runner/issues/13#issuecomment-756577867):

> here is the final result, we are already using it in our CD pipeline.
> ![](https://user-images.githubusercontent.com/1004667/103982407-1be20280-518c-11eb-802b-fc4e141ee3e2.png)

You're the first one I know who started using the action! 
Thank you for sharing and for all the support! 🙌

**Reply by lielran** [reply]
> @lielran shared in [the comment](https://github.com/machulav/ec2-github-runner/issues/13#issuecomment-756577867):
> 
> > here is the final result, we are already using it in our CD pipeline.
> > ![](https://user-images.githubusercontent.com/1004667/103982407-1be20280-518c-11eb-802b-fc4e141ee3e2.png)
> 
> You're the first one I know who started using the action!
> Thank you for sharing and for all the support! 🙌


I'll add to that. 
Run Flyway in order to maintain the DB schema as part of the CD pipeline, just before the deployment it self.

**Reply by machulav** [reply]
And even more from [this comment](https://github.com/machulav/ec2-github-runner/issues/13#issuecomment-757268410) 🙂

> we are using flyway to align our DB schema (rds,pg). the db is running in isolated subnet without(direct) internet access. the easist thing to do is run the migration from within the vpc on a public subnet(application subnet).

**Comment by snussik** [comment]
As I found this action extremely useful and glad, that @machulav created it before I have to )) - here is my first test workflow on it:
<img width="931" alt="Screenshot 2021-01-09 at 16 25 14" src="https://user-images.githubusercontent.com/16715490/104092851-abc0a300-5297-11eb-94fc-76ed5b56391e.png">

<img width="1259" alt="Screenshot 2021-01-09 at 16 25 36" src="https://user-images.githubusercontent.com/16715490/104092855-b8dd9200-5297-11eb-8c18-e3380f561070.png">

<img width="1261" alt="Screenshot 2021-01-09 at 16 25 48" src="https://user-images.githubusercontent.com/16715490/104092860-c561ea80-5297-11eb-895d-0fa3957f7c94.png">

<img width="1259" alt="Screenshot 2021-01-09 at 16 25 59" src="https://user-images.githubusercontent.com/16715490/104092866-ce52bc00-5297-11eb-88a0-5e5a652dd0ae.png">

**Reply by machulav** [reply]
@snussik, many thanks for the feedback and information about your workflow!

May I ask you why do you need to run your workflow on the self-hosted EC2 runner? Why don't the GitHub-hosted runners work for you in this case?

**Reply by snussik** [reply]
Sure! The issue is in nodejs problems with memory and cpu usage. On [quite big datasets](https://github.com/gatsbyjs/gatsby/discussions/28952#discussion-1660918) github runner [specs](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources) are not enough.

**Comment by machulav** [comment]
An example of usage from @winterpixelgames 🙌

<img width="593" alt="image" src="https://user-images.githubusercontent.com/2857712/111353441-fc84bb80-868d-11eb-97fb-c3c03322df9c.png">

https://twitter.com/winterpixelco/status/1371869394318491648

**Comment by machulav** [comment]
@osquery uses the action in one of their automation: https://github.com/osquery/osquery/blob/master/.github/workflows/build_aarch64.yml 😍

Example:
![image](https://user-images.githubusercontent.com/2857712/115514557-e372ba00-a28c-11eb-8136-8b5ccdab7bba.png)

**Comment by M-JobPixel** [comment]
At Jobpixel we've got a test workflow running:
![Screenshot 2021-06-16](https://user-images.githubusercontent.com/67286683/122287203-9a379300-cee8-11eb-94cf-2cbb68f85ba2.png)
Thanks for the plugin

**Comment by myatsko-ledger** [comment]


**Reply by M-JobPixel** [reply]
See issue https://github.com/machulav/ec2-github-runner/issues/48

I think you're suffering from what I was suffering from, i.e. the user who's creds you are using is not an Admin of the repo you're trying to get tokens from.

hth

**Reply by myatsko-ledger** [reply]
Thanks for insight, will check

**Reply by myatsko-ledger** [reply]
> See issue #48
> 
> I think you're suffering from what I was suffering from, i.e. the user who's creds you are using is not an Admin of the repo you're trying to get tokens from.
> 
> hth

It is exactly the same issue indeed! Thx fpr help!

**Comment by ghost** [comment]
Is there a way with the existing code to only stop a running instance, rather than terminating it and starting a new one? We are interested in using this for embedded Linux builds where the build machines depend on large (existing) caches of objects built in earlier build to persist on the build machine.

**Comment by machulav** [comment]
An interesting example from @stas00 and [BigScience Workshop](https://github.com/bigscience-workshop) team, where they try to create an instance in 3 different AZs as the capacity of such a powerful instance is limited and may not be available in one AZ in the required time.

https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/main/.github/workflows/main.yml

**Reply by stas00** [reply]
Might be a good idea to link to a specific SHA of the current config, as this is all new and may change.
i.e.: https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/9e14c02a1dd22e4d36e2ee9a33e44d33774b8de7/.github/workflows/main.yml

plus all credits for this solution go to @jpalomaki - I just adapted his proposal.

**Comment by metola** [comment]
Hi @machulav , thanks for plugin
![image](https://user-images.githubusercontent.com/8111455/132699511-453e2828-c9ce-49d5-a05b-a732ff5dedf0.png)

**Comment by jappyjan** [comment]
at nifty.store (by elbstack GmbH) we use self-hosted runners to be able to use more powerfull runners so that our build time decreases significantly.

<img width="1362" alt="Bildschirmfoto 2021-12-17 um 22 34 43" src="https://user-images.githubusercontent.com/10154260/146610637-b0bf4043-c825-4d6b-8aea-a26874dd95f3.png">

**Comment by InoMurko** [comment]
hiiii, has anyone been able to spawn multiple runners and attach them to a matrix job?
ehmm, matrix spawns multiple concurrent jobs and I want them to use a self-hosted EC2 executioner

edit: one can certainly spawn runners in a matrix strategy, the problem comes with cleaning them up because you essentially need to use `runs-on: [self-hosted]` to pick one of the spawned runners. but because of that, you loose all job outputs so no way to stop the runner after `job job`

anyway to get 
```
label
ec2-instance-id
```
from `runs-on: [self-hosted]`?

**Reply by InoMurko** [reply]
okay figured it out:
the first ephemeral runner builds all containers and uploads image artifacts. the runner stops stop_runner.
a matrix of 6 starts ephemeral runner executioners. these instances write their ids in /tmp/runner/{matrix.id}
a matrix of integration jobs assigns itself to runner executioners - one2one.
stop-executioner waits for integration jobs and downloads /tmp/runner artifacts and kills the one - based on it's own matrix.
```
name: integration

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - '*rc'
      - 'regenesis/*'
  pull_request:
  workflow_dispatch:

jobs:

  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-00b46fa1102c70ff2
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-905870ae
          security-group-id: sg-0855631d714870b32

  start-executioner:
    name: Start self-hosted EC2 executioner
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        include:
        - id: 1
          test-grep-filter: 'tag:rpc'
        - id: 2
          test-grep-filter: 'tag:boba'
        - id: 3
          test-grep-filter: 'tag:nft'
        - id: 4
          test-grep-filter: 'tag:mrf'
        - id: 5
          test-grep-filter: 'tag:other'
        - id: 6
          test-grep-filter: '^((?!tag:).)*$'
    outputs:
      label: ${{ steps.executioner.outputs.label }}
      ec2-instance-id: ${{ steps.executioner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 executioner
        id: start-ec2-executioner-1
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-00b46fa1102c70ff2
          ec2-instance-type: t2.2xlarge
          subnet-id: subnet-905870ae
          security-group-id: sg-0855631d714870b32
      - name: Output the runner meta
        run: |
          mkdir /tmp/runner/
          mkdir /tmp/runner/${{ matrix.id }}
          echo '${{ matrix.test-grep-filter }}' > /tmp/runner/${{ matrix.id }}/filter
          echo ${{ steps.start-ec2-executioner-1.outputs.label }} > //tmp/runner/${{ matrix.id }}/label
          echo ${{ steps.start-ec2-executioner-1.outputs.ec2-instance-id }} > /tmp/runner/${{ matrix.id }}/instance
      - uses: actions/upload-artifact@v2
        with:
          name: runner_info
          path: /tmp/runner/*

  build:
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build the services
        working-directory: ./ops
        run: |
          ./scripts/stats.sh &
          ./scripts/build-ci.sh

      - name: List the images
        working-directory: ./ops
        run: docker images

      - name: Export and upload artifact images
        run: |
          mkdir /tmp/bobanetwork
          for i in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep bobanetwork); do
            docker save -o /tmp/$(echo "$i" | sed s/:/_/g).tar "$i" &
          done
          wait < <(jobs -p)

      - uses: actions/upload-artifact@v2
        with:
          name: boba_images
          path: /tmp/bobanetwork/*.tar

  integration:
    needs:
      - build
      - start-executioner
    runs-on: [self-hosted]
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        include:
        - id: 1
          test-grep-filter: 'tag:rpc'
        - id: 2
          test-grep-filter: 'tag:boba'
        - id: 3
          test-grep-filter: 'tag:nft'
        - id: 4
          test-grep-filter: 'tag:mrf'
        - id: 5
          test-grep-filter: 'tag:other'
        - id: 6
          test-grep-filter: '^((?!tag:).)*$'
    steps:
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: boba_images
          path: /tmp/bobanetwork/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: /tmp/bobanetwork/

      - name: Load artifacts into docker
        run: |
          for f in ${{steps.download.outputs.download-path}}/*.tar; do
            docker load -i $f &
          done
          wait < <(jobs -p)

      - uses: actions/checkout@v2

      - name: Bring the stack up
        working-directory: ./ops
        run: BUILD=2 DAEMON=1 ./up_local.sh

      - name: Wait for the Sequencer node
        working-directory: ./ops
        run: ./scripts/wait-for-sequencer.sh

      - name: Start background logging
        working-directory: ./ops
        run: docker-compose -f docker-compose.yml logs --follow &

      - name: Run the integration tests
        working-directory: ./ops
        run: docker-compose run -e TEST_GREP_FILTER="${{ matrix.test-grep-filter }}" integration_tests

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # required to get output from the start-runner job
      - build # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}

  stop-executioner:
    name: Stop self-hosted EC2 runner
    needs:
      - integration # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        include:
        - id: 1
        - id: 2
        - id: 3
        - id: 4
        - id: 5
        - id: 6
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: runner_info
          path: /tmp/runner/

      - name: Set runner info
        id: runner_info
        working-directory: /tmp/runner/
        run: |
          ls -altr
          cd ${{ matrix.id }}
          cat filter
          echo "::set-output name=label::"$(cat label)
          echo "::set-output name=ec2-instance-id::"$(cat instance)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ steps.runner_info.outputs.label }}
          ec2-instance-id: ${{ steps.runner_info.outputs.ec2-instance-id }}
```

**Comment by kopyl** [comment]
Please record a video on how to use it.
It's not clear to me from this [page](https://github.com/marketplace/actions/on-demand-self-hosted-aws-ec2-runner-for-github-actions#real-user-examples) how to use it.

I don't have time to do all that from instruction, mess up my production server and realize that it's not what I needed. Please record a video.

**Comment by joristork** [comment]
Is the self-hosted runner's output (e.g. linting and test failure details) available from the github actions tab? Is it any different to the output of a github-hosted runner?

**Reply by CryptoGraffe** [reply]
yes same question

**Reply by machulav** [reply]
Please create a new discussion if you have questions not related to the topic.
The topic in this discussion is "Real examples of the action usage" so mark your comments as off-topic.

**Comment by pradeeptalwar** [comment]
Hello  Volodymyr ,

Will you be ok for me to fork off this repo to see if we can include MarketType=spot ?

Kind regards,
Pradeep

**Reply by Dmitry1987** [reply]
[ADMIN] permission to fork was granted ✔️ 

Enjoy! 😁

**Reply by maciejlis** [reply]
Hi @pradeeptalwar,
How are your test results? Can you please share I need to use a powerful instance and it would be cost-effective to use spot instead.

Best regards,
maciuuula

**Reply by pradeeptalwar** [reply]
Hello @maciejlis 

I am really sorry for the late reply. Have not been looking into the GitHub stuff for a while. I hope you managed to get it working for spot instances.

Regards,
Pradeep

**Reply by crohr** [reply]
Spot is very cost-effective, and for workflows < 20-30mins the risk of being interrupted is very low (AWS doesn't bill you if your instance stays up for less than 1h). If you're interested, I'm the author of [RunsOn](https://runs-on.com), which is an alternative to this project, actively maintained.

**Comment by nilesingalls** [comment]
works very nicely, thank you!
![githubrunners](https://user-images.githubusercontent.com/4258353/224552811-ba949931-3a21-44f2-ac49-e62d5530878a.png)

**Comment by elgehelge** [comment]
Anybody who have managed to put these jobs into a reusable component that can be used many times throughout a workflow? 
Eg. (job that uses a small instance) -> (job that uses a GPU) -> (job that uses a large CPU instance)
Would love to see some examples workflows of this kind.

**Reply by Dmitry1987** [reply]
that's easy imho, you just do this:

create a folder near your main workflow and name it lets say "runners", add file "runners/action.yaml" with 

```
# Sub action for the ec2 spawns, parameterized, to avoid duplicating the code for different types of ec2 instances
name: make a new runner
description: new ec2 runner of any type
inputs:
  # parameter provided by main pipeline which calls this action
  server-type: 
    description: server of some kind, like gpu or windows
    required: true
    default: windows

runs:
  using: "composite"
  steps:
      - name: Start runner with GPU support
        id: start-ec2-runner-gpu-flavor
        uses: machulav/ec2-github-runner@v2
        if: ${{ inputs.server-type == 'gpu' }}
        with:
          mode: start
          ec2-image-id: ami-123123123123
          ec2-instance-type: the gpu type you need
          subnet-id:.....
          security-group-id: .....

      - name: Start runner with Windows support
        id: start-ec2-runner-windows-flavor
        uses: machulav/ec2-github-runner@v2
        if: ${{ inputs.server-type == 'windows' }}
        with:
          mode: start
          ec2-image-id: ami-678789789789
          ec2-instance-type: the windows type
          subnet-id:.....
          security-group-id: .....
```

then in the main pipeline you can call it like this

```
    - id: start a runner
      uses: ./.github/workflows/runners
      with:
        server-type: gpu
```

this avoids some duplication and you can manage all runner definitions in one place let's say and even import them as submodules to share with many repos and teams 🔥
