### ISSUE TITLE
stop action fails to find Github runner though the labeled runner does exist

### ISSUE THREAD

**Issue by scottdickerson** [machulav/ec2-github-runner#119]
This results in lots of offline runners piling up in our repository.  The EC2 instance is killed successfully but the runner isn't remove

![image](https://user-images.githubusercontent.com/6663002/197277681-cd094fc6-553e-4c24-99ed-7bafee79a456.png)
```
Run machulav/ec2-github-runner@v2
  with:
    mode: stop
    github-token: ***
    label: shk8d
   <removed for security>
    aws-resource-tags: []
  env:

    AWS_DEFAULT_REGION: <removed>
    AWS_REGION: <removed>
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
AWS EC2 instance <removed-for-security> is terminated
GitHub self-hosted runner with label shk8d is not found, so the removal is skipped
```
