### ISSUE TITLE
Permissions issue on EC2 self-hosted runner

### ISSUE THREAD

**Issue by snussik** [machulav/ec2-github-runner#13]
Hi!
Tried to test your example workflow https://github.com/snussik/ec2-github-runner
But on master commits nothing happens at all.
And VScode linter shows error:
<img width="1277" alt="Screenshot 2021-01-04 at 23 33 42" src="https://user-images.githubusercontent.com/16715490/103577146-4cecd980-4ee5-11eb-8d8c-2c704eada7ca.png">

**Comment by machulav** [comment]
@snussik have you found the issue?

As I see you set up the workflow for the `master` branch. But there are no `master` branch for this repository, the main branch here is `main`. Hope it helps.

**Comment by snussik** [comment]
@machulav hi! Yep, I've discovered it. And I have a new problem now )) When I create remote runner on aws and try to run `npm ci` (or `npm install`), I get:
`npm ERR! correctMkdir failed to make directory /home/github/.npm/_locks`
`npm ERR! code EACCES`
`npm ERR! syscall mkdir`
`npm ERR! path /home/github`
`npm ERR! errno -13`

The commands: `whoami` shows that bash runs under the ` github` user.  

The part of workflow file, is:
```
# Test WF for GA

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_RUNNER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_RUNNER }}
          aws-region: ${{ secrets.AWS_REGION_RUNNER }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v1.0.0
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-02501629bfc260e9c
          ec2-instance-type: t2.micro
          subnet-id: subnet-04850abda92c62906
          security-group-id: sg-0fda70c804d158ece
  do-the-job:
    name: Do the job on the runner
    runs-on: ${{needs.start-runner.outputs.label}} # run the job on the newly created runner
    needs: start-runner # required to start the main job when the runner is ready
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.2
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Build
        run: |
          whoami
          npm ci
```

Is that related to AWS Credentials? I thought that github user runs ints workflow under needed permissons inside the runner instance/
