### ISSUE TITLE
Is there a way to increase volume size of instance created

### ISSUE THREAD

**Issue by Nitish1814** [machulav/ec2-github-runner#212]
Hi,
I have created an AMI with 256 GB snapshot. However when I spinning up EC2 in workflow, it is creating instance with 8GB volume only. Do I need to specify some additional input in 'with' ?

```
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ inputs.PAT }}
          ec2-image-id: ami-xyz
          ec2-instance-type: t3.xlarge
          subnet-id: subnet-xyz
          security-group-id: sg-xyz
```
Regards,
