### ISSUE TITLE
Github actions results doesn't match manual equivalent.

### ISSUE THREAD

**Issue by andreehultgren** [machulav/ec2-github-runner#73]
I have spent a few days troubleshooting this issue, and it seems to be an issue with the GitHub runner.

The action involves
- Pull code
- Build docker images (frontend and backend)
- Run docker images (frontend and backend)
- Run RPA script to virtually interact with the full-stack application.

The following is a simplification of the code. Many packages are pre-installed in the AMI image (docker, database client e.t.c.)

```yaml
name: RPA deep test
on:
  push:
    branches:
      - dev
jobs:
  start-runner:
    name: Instanciate temporary EC2 instance
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.RPA_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.RPA_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.RPA_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.RPA_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ${{ secrets.AMI_IMAGE }}
          ec2-instance-type: ${{ secrets.INSTANCE_TYPE }}
          subnet-id: ${{ secrets.SUBNET }}
          security-group-id: ${{ secrets.SECURITY_GROUP }}
  do-the-job:
    name: Perform tests
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
    steps:
      - name: Enable docker permissions
        id: docker-permission
        run: sudo chmod 666 /var/run/docker.sock

      - name: Clone repo
        id: git-clone-repo
        run: git clone https://${{secrets.GH_USER}}:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/foo-project/foo.git --branch=${GITHUB_REF##*/}

      - name: Build frontend image
        id: build-frontend-image
        run: cd foo && docker build -t frontend-test:latest frontend/.

      - name: Build backend image
        id: build-backend-image
        run: cd sq-web-app && docker build -t backend-test:latest backend/.

      - name: Run frontend image
        id: run-frontend-image
        run: docker run --name frontend -p 3000:80 --env BACKEND=http://localhost:8080/api -d frontend-test:latest

      - name: Run backend image
        id: run-backend-image
        run: docker run --name backend -d -p 8080:8080  backend-test:latest

      - name: Run tests
        id: robot-test
        run: |
          cd sq-web-app
          sudo apt install -y python3-pip
          pip3 install robotframework
          pip3 install robotframework-browser
          python3 -m Browser.entry init
          python3 -m robot test/0*.robot

  stop-runner:
    name: Terminate EC2 Instance
    needs:
      - start-runner # required to get output from the start-runner job
      - do-the-job # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.RPA_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.RPA_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.RPA_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.RPA_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
```

When this is executed in GitHub actions, the robot script cannot find the backend server. 

When I manually execute these commands with identical settings, everything works flawlessly.

Why does the GitHub runner not execute commands the same way as if I were to SSH into an instance and execute the commands manually? (as you would expect)
