### ISSUE TITLE
Hello World Job Completes With a Failed Result on the EC2 Instance

### ISSUE THREAD

**Issue by shahzadlone** [machulav/ec2-github-runner#91]
I have followed all the instructions that are mentioned in the README.md but the hello world job results in failure for me.

Here is the output from the `EC2 Serial Console`:
![image](https://user-images.githubusercontent.com/30120428/149406512-aef030c5-71bc-4aa2-a704-36baa12c3aa6.png)

Here is the output from the GitHub action (it stays stuck here):
![image](https://user-images.githubusercontent.com/30120428/149406546-645763f9-f8bd-44aa-9ca8-6ffa9ccce80e.png)

Here is what's in my `.github/workflows/aws-ec2-job.yml` file:
```
name: aws-ec2-job

on: pull_request

jobs:

  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.REPO_SCOPE_PAT }}
          ec2-image-id: ${{ secrets.EC2_IMAGE_ID }}
          ec2-instance-type: t3.xlarge
          subnet-id: ${{ secrets.SUBNET_ID }}
          security-group-id: ${{ secrets.SECURITY_GROUP_ID }}

  aws-ec2-job:

    name: run the benchmarks on the runner
    needs: start-runner # required to start the main job when the runner is ready

    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner

    steps:
      - name: Hello World
        run: echo 'Hello World!'

  stop-runner:

    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # required to get output from the start-runner job
      - aws-ec2-job # required to wait when the main job is done

    runs-on: ubuntu-latest

    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.REPO_SCOPE_PAT }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}

```
